name: Test ECS Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, ecs, linux]

    steps:
      - name: Check runner
        run: echo "Running on ECS self-hosted runner!"

      - name: Check AWS CLI
        run: aws --version

      - name: Check environment
        run: |
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"
